let imagePath: string = 'assets/images'
let iconPath: string = 'assets/icons'

export const FilePath = {
    Image: {
        user: `${imagePath}/user_img.svg`,
    },

    Icon: {
        arrow_nav: `${iconPath}/arrow_nav.svg`,
        arrow_up: `${iconPath}/arrow_up.svg`,
        arrow_up_solid: `${iconPath}/arrow_up_solid.svg`,
        filter: `${iconPath}/filter.svg`,
        camera_solid: `${iconPath}/camera_solid.svg`,
        caret_down_solid: `${iconPath}/caret_down_solid.svg`,
        check: `${iconPath}/check.svg`,
        check_circle_blue: `${iconPath}/check_circle_blue.svg`,
        check_circle_solid: `${iconPath}/check_circle_solid.svg`,
        check_white: `${iconPath}/check_white.svg`,
        chevron_circle_left_solid: `${iconPath}/chevron_circle_left_solid.svg`,
        chevron_circle_right_solid: `${iconPath}/chevron_circle_right_solid.svg`,
        circle_empty_blue: `${iconPath}/circle_empty_blue.svg`,
        close: `${iconPath}/close.svg`,
        cog_solid: `${iconPath}/cog_solid.svg`,
        comment_dots_regular: `${iconPath}/comment_dots_regular.svg`,
        cross_solid: `${iconPath}/cross_solid.svg`,
        download_app_store: `${iconPath}/download_app_store.svg`,
        download_solid: `${iconPath}/download_solid.svg`,
        facebook: `${iconPath}/facebook.svg`,
        facebook_2: `${iconPath}/facebook_2.svg`,
        file_pdf_solid: `${iconPath}/file_pdf_solid.svg`,
        file_word_solid: `${iconPath}/file_word_solid.svg`,
        gmail: `${iconPath}/gmail.svg`,
        google: `${iconPath}/google.svg`,
        google_store: `${iconPath}/google_store.svg`,
        image: `${iconPath}/image.svg`,
        ios_store: `${iconPath}/ios_store.svg`,
        linkedin: `${iconPath}/linkedin.svg`,
        linkedin_2: `${iconPath}/linkedin_2.svg`,
        lock_solid: `${iconPath}/lock_solid.svg`,
        logout: `${iconPath}/logout.svg`,
        minus: `${iconPath}/minus.svg`,
        path_up: `${iconPath}/path_up.svg`,
        path_up_solid: `${iconPath}/path_up_solid.svg`,
        pen_solid: `${iconPath}/pen_solid.svg`,
        pen_solid_dark: `${iconPath}/pen_solid_dark.svg`,
        play_store: `${iconPath}/play_store.svg`,
        plus: `${iconPath}/plus.svg`,
        plus_solid: `${iconPath}/plus_solid.svg`,
        question_circle_regular: `${iconPath}/question_circle_regular.svg`,
        question_circle_regular_dark: `${iconPath}/question_circle_regular_dark.svg`,
        radio: `${iconPath}/radio.svg`,
        sign_out_alt_solid: `${iconPath}/sign_out_alt_solid.svg`,
        tag_cross: `${iconPath}/tag_cross.svg`,
        trash_alt_solid: `${iconPath}/trash_alt_solid.svg`,
        twitter: `${iconPath}/twitter.svg`,
        uncheck: `${iconPath}/uncheck.svg`,
        upload_solid: `${iconPath}/upload_solid.svg`,
        user_edit_solid: `${iconPath}/user_edit_solid.svg`,
        print_solid: `${iconPath}/print_solid.svg`,
        star_regular: `${iconPath}/star_regular.svg`,
        star_solid: `${iconPath}/star_solid.svg`,
        check_regular: `${iconPath}/check_regular.svg`,
    }
}
